### ISSUE TITLE
Not working in 1.10.2

### ISSUE THREAD

**Issue by Jonny999999** [ArdiMaster/SunBurnsTrees#10]
Hello,
i just updated my server to the latest Spigot version (CraftBukkit version git-Spigot-de459a2-51263e9 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT). I can see the plugin in the plugin list (/pl) and its green but it does not work.
I get this error on startup:
> [11:44:32 ERROR]: Error occurred while enabling SunBurnsTrees v0.10.0 (Is it up to date?)
java.lang.NullPointerException
        at org.bukkit.Location.getBlock(Location.java:87) ~[spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
        at me.ardimaster.sunburnstrees.SunBurnsTrees.loadBlocks(SunBurnsTrees.java:194) ~[?:?]
        at me.ardimaster.sunburnstrees.SunBurnsTrees.onEnable(SunBurnsTrees.java:57) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugin(CraftServer.java:373) [spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:323) [spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:412) [spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:377) [spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:332) [spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:271) [spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535) [spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]

Hm i remember it once worked in 1.10.2 already but now it doesnt anymore... Could it still be a problem with a new Spigot update?  If its not too much work i would be verry happy if you could update this awesome plugin :)
-- jonny999999

**Comment by awlck** [comment]
OK. So I did some research on the matter, and this error seems to occur if my plugin attempts to access a world that doesn't exist on the server.
When you updated your server, did you by any chance rename and/or remove one or more worlds? If so, please try to delete the blocks.yml file and see if it works (note however that this will obviously make you "start over" with no blocks being monitored).

**Comment by Jonny999999** [comment]
Thanks for your answer,
you are right! I renamed the world during the update...
I just deleted the blocks.yml as you said and it immediately worked fine again :) So the plugin works verry well in 1.10.2.
wow that was my mistake im so sorry... I could have found out that by myself^^
